name: gym-retro
channels:
  - pytorch
dependencies:
  - pytorch
  - torchvision
  - tensorflow-gpu
  - cython
  - pip:
    - moviepy
    - tensorforce==0.4.2
    - gym-retro  # Must be version 0.6 from master
