name: gym-retro
channels:
  - pytorch
dependencies:
  - pytorch
  - torchvision
  - tensorflow-gpu
  - cython
  - scikit-image=0.14.0
  - opencv=3.4.2
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - keras-gpu=2.2.2
  - pip:
    - moviepy==0.2.3.5
    - gym-retro==0.6.0
    - ray[debug]==0.6.0
    - lz4==2.1.0
