name: gym-retro-cpu
channels:
  - pytorch
dependencies:
  - pytorch=1.0.0
  - torchvision=0.2.1
  - tensorflow=1.10.0
  - cython=0.29.2
  - scikit-image=0.14.0
  - opencv=3.4.2
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - keras=2.2.2
  - pip:
    - moviepy==0.2.3.5
    - gym-retro==0.6.0
    - ray[debug]==0.6.3
    - lz4==2.1.0
    - gym[atari]==0.11.0
