name: gym-retro
channels:
  - pytorch
dependencies:
  - pytorch
  - torchvision
  - tensorflow-gpu
  - cython
  - scikit-image=0.14.0
  - opencv=3.4.2
  #- jupyter=1.0.0
  #- nb_conda=2.2.1
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - pip:
    - moviepy
    - gym-retro==0.6.0
    - ray==0.5.3
    - lz4==2.1.0
